### ISSUE TITLE
[Feature Request] Ability toggle "All good 👍" comment

### ISSUE THREAD

**Issue by adamjuhasz** [restyled-io/restyled.io#171]
When implementing a custom image (or any config change), I don't have a way to check functionality of Restyled unless I force an error that activates a linter or formatter. In essence, I don't know if I'm not doing anything incorrectly or restyled is not working.

It would be nice to have an "all good" comment after each commit checked to verify it's all working. Of course this could be really noisy so on/off switch would be great (or limit per PR?).

**Comment by pbrisbin** [comment]
Hmm, you should get a green PR status with a link to the build, whose log
should show enough to know if things are working. Are you seeing that?

**Comment by adamjuhasz** [comment]
I see "retry job" on the repo page on the restyled.io site now that I set my status as "Public" on the org, thanks for that! But I don't see it as a check on GitHub...

![image](https://user-images.githubusercontent.com/757940/60630004-fe6cf500-9dac-11e9-81de-cc01411e4a93.png)


![image](https://user-images.githubusercontent.com/757940/60629918-a7672000-9dac-11e9-99d9-2b2aa82a8523.png)

**Comment by pbrisbin** [comment]
Ah yeah, the Checks tab is different and Restyled doesn't (yet) integrate
with it, but there should be a green Status at the bottom of the
Conversation tab that says "restyled ... no differences".

That should link to the Job, but it also looks like you found your way to
Jobs anyway from the Profile page.

The other part is you will need to have a file changed in the PR that is in
the includes of the Restyler you are trying to exercise, since Restyled is
designed to only operate on changed files.

Lastly, I can enable debug on a repository for you, which can be useful if
you're actively developing a Restyler, or contributing to the project in
general. There are caveats I can go into if you're interested, but I
wouldn't be able to do it till Monday anyway.

Hope this helps!

**Comment by adamjuhasz** [comment]
No worries, don't do extra work on my behalf I can use the jobs page! Appreciate it though. I don't see a status anywhere, I'll just use the jobs page.

![image](https://user-images.githubusercontent.com/757940/60630422-e1d1bc80-9dae-11e9-9c25-8934e632085e.png)

**Comment by pbrisbin** [comment]
Oh the statuses UI goes away now that it's been merged. If you click on any
of the green check marks on those commits, is Restyled in there? Or maybe
you can look for it in your next opened PR.

**Comment by adamjuhasz** [comment]
Hmm I'm not seeing any status indicators on the PR page, but you've already spent way too much time on this and there's a simple workaround...

![image](https://user-images.githubusercontent.com/757940/60631153-df716180-9db2-11e9-8fb1-3be1114d3618.png)

**Comment by pbrisbin** [comment]
Haha, no worries. Now I'm thinking this is a bug report, not feature
request! I'll investigate more after the weekend.

**Comment by pbrisbin** [comment]
Hey there, just getting back to this... Could you send me the `.restyled.yaml` that was in the branch for PR 26?

**Comment by adamjuhasz** [comment]
```
---
enabled: true
auto: false
remote_files: []
comments: true
statuses: false
request_review: null
labels: []
restylers:
  - hlint:
      include:
        - "**/src/*.hs"
```

**Comment by pbrisbin** [comment]
Well that explains that!

```yaml
statuses: false
```

**Comment by adamjuhasz** [comment]
Eek! 🤦‍♂️ for the second time. This is not my best foot forward

**Comment by adamjuhasz** [comment]
Works perfect, see it now! Thanks so much

![image](https://user-images.githubusercontent.com/757940/60832368-946b9b80-a170-11e9-90fc-517ef8c73cd0.png)

**Comment by pbrisbin** [comment]
Aha! Don't feel bad, this is the best outcome for this Issue IMO :)

Documentation point taken, I'll take a look at it and try to clarify.
