### ISSUE TITLE
Reopen restyled pull request when pull request is updated instead of opening a new one

### ISSUE THREAD

**Issue by wirew0rm** [restyled-io/restyled.io#191]
Hey there, first of all, thank you for restyled.io, it is really the nicest method to do restyling in a comprehensible and unobtrusive way we found :+1: 

I just found one small annoyance: We often have long lived pull requests, which get refactored and modified multiple times. Often the formatting changes multiple time from "found differences" to "no differences" and back, each time opening a new pull request. It would be a lot nicer, if restyled.io would just reopen the merged/closed pull request, especially since pull requests cannot be deleted.

**Comment by pbrisbin** [comment]
This is a great idea, and shouldn't be too hard to implement. The application already [has access to the (potential) Restyled PR](https://github.com/restyled-io/restyler/blob/master/src/Restyler/Setup.hs#L43-L47), so we just need to update the query so that it finds it even if Closed. Once we do that, we can then update [the code that updates-or-opens the Restyled PR](https://github.com/restyled-io/restyler/blob/master/src/Restyler/Main.hs#L65-L72) to include re-opening that existing Restyled PR if it's closed.

**Comment by pbrisbin** [comment]
I had to revert this, so I'm re-opening.

GitHub was consistently giving us _422 Unprocessable Entity_ on our re-open requests, saying `state` could not be changed. I suspect it has to do with deleting and re-creating the underlying branch, but I haven't confirmed that through testing.

I may not have time to make this feature, but PRs are welcome if they come with manual testing to ensure it works.
