### ISSUE TITLE
Feature: open PRs on the fork an unstyled PR came from

### ISSUE THREAD

**Issue by iphydf** [restyled-io/restyled.io#201]
Instead of making a second PR on the target repo, a more easily actionable request would be if restyled created a branch in the target/upstream repo (as it does now) and then sent a PR to the originating fork. This also reduces clutter on the target repo, and avoids artificially inflating the number of PRs going through the repo.

**Comment by iphydf** [comment]
I assume this has been considered, so what's blocking this?

**Comment by pbrisbin** [comment]
Totally agree the Forked workflow is unfortunate.

> sent a PR to the originating fork ... so what's blocking this?

In order to do this, Restyled would have to be installed on the fork too, and there's no such guarantee. It's probably possible to check, and do this if we happen to be installed there, but at this point the complexity is not worth it IMO.

**Comment by leotrs** [comment]
We just tried this and... it is unfortunate indeed. The bot opens a copy PR in the target (and not a stacked PR in the originating fork) even when the bot is also installed in the originating fork!

**Comment by pbrisbin** [comment]
Yeah, sorry about that. Things haven't changed from:

> Restyled would have to be installed on the fork too, and there's no such guarantee. It's probably possible to check, and do this if we happen to be installed there, but at this point the complexity is not worth it IMO

But I can elaborate.

It comes down to how Restyled is architected:

- We get a hook that the PR has been opened in the Upstream
- We get a token for our App (which is specific to that Installation)
- We invoke `restyler`, passing it that token
- It does what it does, with operations all using that token

We would have to add _a lot_ of complexity to make this work...

- The webhook handler (which does almost nothing now) would need to understand Forks, find the Upstream vs the Fork and see if we can get an Installation token for both
- `restyler` would need more options and to read more environment variables because it now needs to operate in one repository, while opening a PR in another
- `restyler` internally needs to audit all of its steps (checking for existing Restyle PRs, adding/removing Comments, Statuses, Review Request behaviors, etc) to ensure they are working on the right repository for the new scenario

Nothing is impossible, but it's a lot. So you have to consider the likelihood that we are in fact installed on both repositories involved, because if we aren't, none of this is possible at all. My gut is it's quite low, but perhaps I could measure that somehow.

It's frustrating because the frequency of Restyled needing to work on Forks is high -- so this seems like a valuable problem to solve, but the only technical way it could work is for us to be installed on both repositories, and frequency for that is (I think) very low, meaning the ROI is just not there.

One option would be to build this feature, which only works if we're installed in both places. Then, in the case where we're _not_ installed in both places, have a Call to Action to the Fork author to install us "for a better experience." This has the upsides of (a) driving more installations and (b) providing a better experience for our users. (b) is _very_ compelling, however, it has a number of downsides:

1. We have to build the whole thing with only the _hope_ it'll actually lead to those outcomes
2. The "better experience" is to the Upstream developer, but the burden of "opting in" is placed on the Fork author. This feels poorly aligned, and so unlikely to succeed

If it were possible to build this in a more isolated (i.e. reversible) way, I'd be game to go for it and see how it works out. But (as you can see above), it would require re-architecting up and down the stack (AFAICT).

Nothing's off the table, but that is the current status, as transparently and detailed as I'm able to describe it.

One last point: this feature would almost exclusively benefit OSS users. It's exceedingly rare that a private repository sees outside contributors via Forks. That's 1000% not the sole reason I'm unable to develop the feature, I love OSS and want to support it well. But, again, because the likelihood of us being installed in both places is low, it just doesn't seem the effort would actually provide that benefit. That said, this is exactly why Restyled is itself OSS -- if the community wants to solve this problem, I'm more than happy to help on-board anyone into the code base and spend my time trying to make them successful building it.

**Comment by leotrs** [comment]
Thank you for the thorough and thoughtful explanation! I will keep looking for ways in which to use this awesome bot :)

**Comment by pbrisbin** [comment]
I'm re-opening this feature because [the way we do it now is not safe](https://github.com/restyled-io/restyled.io/wiki/2022.08.03-Attack-on-Forked-PRs), so we either have to implement something as describe here or simply not support Restyled of fork PRs in OSS projects -- since that's by far the most popular use of Restyled today, I think the choice is pretty clear.

So, here's how I think it could work.

1. We slim `restyler` down to never expect or handle a fork

   It will always run the path of opening a PR-from-PR in the same repository as the `head` (not `base` like today). This should be a (pretty huge) deletion in code/complexity, and we can do it right away since the current fork-handling code is unsafe. :axe: 

1. We update `agent` (the thing that kicks off `restyler`) to handle forks when possible

   It would: try to locate the repository of the contributor and its installation, if it also happens to be using Restyled, then kick off `restyler` as usual, just with that token/repo/pr as arguments.

1. Handle the case of no installation with a hard up-sell :wink: 

   If we don't have the access to do the thing, we should error the original PR with all sorts of details about how Restyled _could_ work if the contributing user installed it: it'll make your contribution more likely to be accepted, and hey you might even like this thing on all your projects. And instructions on what to do after installing (we may need a formal retry, or we could just suggest the new-commit-push flow).

So, if the contribution is coming from someone who happens to have Restyled set up for themselves the workflow is all around improved -- it's no different than the non-fork workflow. If the contribution is from someone who doesn't, the PR gets an error status with lots of details about how to and why that contributor should move to the former camp -- and hopefully they do.

Thoughts?

**Comment by pbrisbin** [comment]
Yeah, so my [original comment](https://github.com/restyled-io/restyled.io/issues/201#issuecomment-682069733) about the complexities involved was not wrong. We can't "just run restyler in the fork repository" even if we can find an extant installation. Restyler will always need to be aware of both installations because it has to talk differently for different things...

- Clone in the fork repository using the head token
- API queries about the PR with the base token
- API queries about the Restyle PR with the head token

It wouldn't be so bad if we just cloned with one token (the fork) and talked to the API in the other (the base), but having to take different API actions with different tokens is a massive pain.

Even something as simple as putting the `#42` link into the Restyle PR description now needs to be `{owner}/{name}#42` to link correctly to the base repository. I can't imagine what else there is.

At first I thought I could make some headway here in the next few days, but now I'm back to being overwhelmed.

**Comment by CAD97** [comment]
While it might not fully generalize and _always_ work[^1], the app could create [a code review with ```` ```suggestion ```` blocks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request?tool=webui#starting-a-review) to suggest patches to the PR which the author can then [apply individually or as a batch from the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes).

[^1]: There's a limit to the context in which you're able to make review comments, and style fixes aren't 100% guaranteed to be localized to just within that context of the PR diff. But it's a fairly safe assumption that *most* formatting fixes *will* be, since the project should already be reasonably formatted, and even if we're migrating in to a style update, PRs generally won't want to be fixing style issues outside of the scope of code they're already touching.
