### ISSUE TITLE
Restyled is breaking shell scripts

### ISSUE THREAD

**Issue by JimmySnails** [restyled-io/restyled.io#205]
restyled suggests changes to certain files in my branch, that breaks them.
in this case, gradlew is changed and will no longer work.

https://github.com/CytopiaTeam/Cytopia/pull/562

Is there a way to skip folders in restyled? in our case, when i merge this PR this would break all consecutive restyled PRs

**Comment by pbrisbin** [comment]
Absolutely! You can configure Restyled to avoid files or folders completely or adjust the files and folders for a specific Restyler. You can see all the details here:

https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled

### Excluding from all Restylers

If you really want Restyled to exclude a folder completely, you can alter the `exclude` option. I would recommend maintaining the defaults and adding your own:

https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#exclude

```yaml
exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*"
  - "platforms/android/**/*" # new, whole folder
  - "platforms/android/gradlew" # or just the file
```

### Excluding from a specific Restyler

If you take a look at the individual commits of the Restyled PR,

https://github.com/CytopiaTeam/Cytopia/pull/562/commits

And identify which Restyler is breaking which file(s), you could be more targeted by adjusting the `include` option of just that Restyler to avoid just that file. For example, to not Restyle `gradlew` with `shfmt`:

https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled#restylers, https://github.com/restyled-io/restyled.io/wiki/Available-Restylers#shfmt

```yaml
restylers:
  - shtfmt:
      include:
      include:
        - "**/*.sh"
        - "**/*.bash"
        - "!platforms/android/gradlew" # new
  - "*"
```

:warning: I just realized `shfmt` in specific also picks up extension-less scripts by shebang and that may interact strangely with this `!exclude` pattern. If that's the case, this approach may not work and I'd consider that a bug to fix. If so, please use the first option (`exclude`) as a workaround.

All that said, would you mind telling me a little more about how `gradlew` breaks? Restyled just wrapos the separate [`shfmt`](https://github.com/mvdan/sh) project, so if it's making changes that break functionality in a shell script, I'm sure that'd be a bug that project would like to know about!

**Comment by JimmySnails** [comment]
Thank you!

i think for my needs it'd be best to exclude the whole android subfolder as it consists of java and other stuff... 

this is the error message on the modified file
```
└─ $ ▶ ./gradlew 
./gradlew: line 59: cd: "./: No such file or directory
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

caused by this change:
```
cd "`dirname \"$PRG\"`/" >/dev/null	
```
to
```
cd "$(dirname \""$PRG"\")/" >/dev/null
```

Here's the diff
https://github.com/CytopiaTeam/Cytopia/pull/562/files#diff-99bc8bc69a1df8df5c929ee55588270e

tbh i'm not good with shellsripts and this is a copy pasta script i found on the internet... (i think it was provided by SDL2?)  so i can't tell you why exactly this is hapenning.

**Comment by pbrisbin** [comment]
Thanks for those details! That is definitely an odd line of shell, particularly the escaped `\"`s. It seems the programmer didn't realize that being inside the backticks is not part of the overall string, so the quotes around the `$PRG` argument shouldn't be escaped.

It's a bit like if you did

```rb
chdir(dirname("\"" ++ PRG ++ "\""))
```
In a more normal language.

Unlike a more normal language, the over-escaping isn't harmful (yet) since the Shell is generally forgiving of such things and kind of evaluates everything as a big string anyway.

The correct way to write that would've been,

```sh
cd "`dirname "$PRG"`/" >/dev/null
```

`shfmt` applying the "prefer `$( )` over backticks" rule would've made it,

```sh
cd "$(dirname "$PRG"/)" >/dev/null
```

Which would work fine.

Instead, you get:

```sh
cd "$(dirname \"$PRG\"/)" >/dev/null
```

This is actually still just as valid as the original, but then `shellharden` kicked in to fix the fact that `$PRG` is technically not quoted (the escaped quotes don't count). Once it "fixes" that, you get:

```sh
cd "$(dirname \""$PRG"\"/)" >/dev/null
```

And now the shell is _actually_ invalid, and with `PRG=./` it's (for some reason) evaluated as,

```
cd "\"./" >/dev/null
```

A directory literally named `"./`, which does not exist.

For what it's worth, I generally find `shellharden` to be not-great in terms of false positives, over quoting, and edge-cases like this. I'm considering disabling it by default.

---

If (as it sounds like) you don't particularly work in Shell and you don't care how any copy-pasta shell scripts are styled, you could just disable those Restyler,

```yaml
restylers:
  - shfmt:
      enabled: false
  - shellharden:
      enabled: false
  - "*"
```

Or, if you only care about one specific Restyler, you could configure so only that runs,

```yaml
restylers:
  - clang-format
```

(Note the omission of `"*"` in this case)
