### ISSUE TITLE
Configurable commit messages

### ISSUE THREAD

**Issue by SaidBySolo** [restyled-io/restyled.io#212]
I am writing a commit message according to the commit convention.

Hopefully restyled will follow it.

**Comment by pbrisbin** [comment]
Unfortunately, that's not possible today, but it would be an easy thing to add. I'm thinking about a new key in `.restyled.yaml`:

```yaml
commit_template: |
  Restyled by ${restyler.name}
```

- Would (something like that) work for your needs?
- Do you have any opinions on the specifics? I.e. how the interpolation should work and/or what values should be interpolate-able?

There are lots of places along the simple-vs-featureful spectrum for that second point, so I'm interested in getting others' perspectives.

**Comment by SaidBySolo** [comment]
That's correct

A good example I think is https://dependabot.com/docs/config-file/#commit_message

**Comment by pbrisbin** [comment]
> A good example I think is...

Thanks for that link, that approach is a little different than what I'm thinking. It's both more complex and less useful (IMO):

1- "Dependabot will attempt to detect your commit message preferences and use those"

I think this is just too much complexity, so I'd rather not build it at this point. If someone contributed the feature and wanted to build this, I wouldn't block it though.

2- Fixed "options" (e.g. prefix, prefix-this-or-that, include-scope) instead of fully customized (e.g. a template)

It could be related to the fact that they try to do (1) and so have to limit what they are able to infer from history, but I actually think an interpolated template would be less complexity to build and provide the user complete flexibility. Again, though if someone wanted to contribute this feature and go the dependabot route, I wouldn't block it.

So yeah, if I tackle this, I think the snippet I showed above and the implied functionality is how I'd like to build it.

Hopefully that'd be OK with you!

**Comment by SaidBySolo** [comment]
Oh, I was misunderstanding the snippet

I think this snippet method is much more flexible and simpler than dependabot.

If you apply that method, I can use it like this

```yaml
commit_template: |
  style: ${restyler.name}
```

yes very simply
