### ISSUE TITLE
Ignore Symlinks

### ISSUE THREAD

**Issue by rwalker-apple** [restyled-io/restyled.io#213]
#### Problem
Repositories with symbolic links that point upwards (e.g. https://github.com/project-chip/connectedhomeip/blob/master/examples/wifi-echo/server/esp32/third_party/connectedhomeip) send restyled into an infinite loop.

#### Proposed Solution
Ignore symlinks.

**Comment by pbrisbin** [comment]
For context, the last time someone ran into this we changed how/when `exclude` is applied, so that users can exclude symlinks successfully to avoid this issue.

```yaml
exclude:
  - "**/*.patch"
  - "**/node_modules/**/*"
  - "**/vendor/**/*"
  - ".github/workflows/**/*" # https://github.com/restyled-io/restyler/issues/73
  - "any/symlinks/here"
```

I can't immediately see any downsides to having Restyler just blanket-ignore them itself. Will we miss things to restyle? Is it possible a PR could include a symlink as a changed file and not include the target file as changed too? If such a case is possible and happens, would it be bad for Restyler to ignore it rather than restyle it (or its target)?

**Comment by rwalker-apple** [comment]
> For context, the last time someone ran into this we changed how/when `exclude` is applied, so that users can exclude symlinks successfully to avoid this issue.

Yes, is the approach we're following as well, but any new symlinks not covered by the exclusion sends restyler away forever without much indication of why the entire project is stuck.  Part of the problem we had was that we didn't have a comment in our .restyled.yaml saying "here be symlinks! stay away!", those lines got removed and we ended up stuck again.


> I can't immediately see any downsides to having Restyler just blanket-ignore them itself. Will we miss things to restyle? Is it possible a PR could include a symlink as a changed file and not include the target file as changed too? If such a case is possible and happens, would it be bad for Restyler to ignore it rather than restyle it (or its target)?

I thought about this briefly.  I couldn't come up with a case where restyler would ever have to follow a symlink to get expected behavior.

Another consideration for symlinks: what is restyler's behavior if the link points outside of the repository?

**Comment by pbrisbin** [comment]
Yeah, that's all fair. I think avoiding symlinks is a good idea. Shouldn't be too hard either, since we already filter non-existent files (which show up do to removals as changes), so it should just be a new check there.

It will require some book-keeping in the form of a new method in the `HasSystem` type class, I think.

**Comment by rwalker-apple** [comment]
HasSystem as a search term shows only this issue.

https://github.com/restyled-io/restyled.io/search?q=HasSystem&unscoped_q=HasSystem

Where does one go to tackle this?

**Comment by pbrisbin** [comment]
That search was in `restyled.io` which is the web app that receives webhook events and kicks off Restyler jobs (as well as serves any user-facing pages). This change would be in the [`restyler`](https://github.com/restyled-io/restyler) project, which is the CLI that actually does the work. Specifically, we'll need to expand [this check](https://github.com/restyled-io/restyler/blob/master/src/Restyler/Restyler/Run.hs#L235) to look for not just a file, but a non-symlink file. And the `HasSystem` class is defined here: https://github.com/restyled-io/restyler/blob/04976848780e251ad09aabfc58bee8a07e8cb783/src/Restyler/App/Class.hs#L31.

**Comment by pbrisbin** [comment]
Hey @rwalker-apple, just checking in on this. Are you planning to implement, or should I consider it available for me to pick up?

**Comment by rwalker-apple** [comment]
I looked at it briefly to see if I could re-constitute some of my Haskell, but failed miserably.  All yours :-( .
