### ISSUE TITLE
I have been removed, and it is still undergoing a state check

### ISSUE THREAD

**Issue by DrAugus** [restyled-io/restyled.io#298]
![1655793782986](https://user-images.githubusercontent.com/34206897/174733694-ebac3963-51d2-4880-9e2e-a92acba76e92.png)

**Comment by DrAugus** [comment]
https://github.com/restyled-io/restyled.io/wiki/Disabling-Restyled

**Comment by pbrisbin** [comment]
Are you referring the yellow _Expected_ status?

If so, that's because you've set up Restyled as a _Required Status_ (Settings > Branches > Branch protection rules), so GitHub will display that until it receives such a status. It will be forever yellow since Restyled is in fact not running. This is a GitHub thing, outside of Restyled's control.

I've not seen any Jobs for any repositories under your user since 6/18. If whatever steps you've taken were taken near/after then, then everything appears good to me. If not, we can dig in further. I'll need to know what actual steps you've taken and the link to a Job or Jobs that have run unexpectedly.

**Comment by DrAugus** [comment]
Thanks. It's my fault, sorry. 

![1655904075370](https://user-images.githubusercontent.com/34206897/175039702-2e0a696c-e949-43ff-8956-7cb8484fa527.png)
